Blog-Web/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.CoreLayer.DTOs.Categories;
using Blog.CoreLayer.Services.Categories;
using Blog.CoreLayer.Utilities;
using Blog_Web.Areas.Admin.Models;
using Blog_Web.Areas.Admin.Models.Categories;

namespace Blog_Web.Areas.Admin.Controllers
{
    public class CategoryController : AdminControllerBase
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {
            return View(_categoryService.GetAllCategory());
        }

        [Route("/admin/category/add/{parentId?}")]
        public IActionResult Add(int? parentId)
        {
            return View();
        }

        [HttpPost("/admin/category/add/{parentId?}")]
        public IActionResult Add(int? parentId, CreateCategoryViewModel createViewModel)
        {
            createViewModel.ParentId = parentId;
            var result = _categoryService.CreateCategory(createViewModel.MapToDto());

            return RedirectAndShowAlert(result, RedirectToAction("Index"));
        }

        public IActionResult Edit(int id)
        {
            var category = _categoryService.GetCategoryBy(id);
            if (category == null)
                return RedirectToAction("Index");

            var model = new EditCategoryViewModel()
            {
                Slug = category.Slug,
                MetaTag = category.MetaTag,
                MetaDescription = category.MetaDescription,
                Title = category.Title,

            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, EditCategoryViewModel editModel)
        {
            var result = _categoryService.EditCategory(new EditCategoryDto()
            {
                Slug = editModel.Slug,
                MetaTag = editModel.MetaTag,
                MetaDescription = editModel.MetaDescription,
                Title = editModel.Title,
                Id = id
            });
            if (result.Status != OperationResultStatus.Success)
            {
                ModelState.AddModelError(nameof(editModel.Slug), result.Message);
                return View();
            }
            return RedirectToAction("Index");
        }


        public IActionResult GetChildCategories(int parentId)
        {
            var categoy = _categoryService.GetChildCategories(parentId);

            return new JsonResult(categoy);
        }
    }
}

Blog-Web/Areas/Admin/Controllers/PostController.cs
using Blog.CoreLayer.DTOs.Posts;
using Blog.CoreLayer.Services.Posts;
using Blog.CoreLayer.Utilities;
using Blog_Web.Areas.Admin.Models.Posts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog_Web.Areas.Admin.Controllers
{
    public class PostController : AdminControllerBase
    {
        private readonly IPostService _postService;

        public PostController(IPostService postService)
        {
            _postService = postService;
        }

        public IActionResult Index(int pageId = 1, string title = "", string categorySlug = "")
        {
            var param = new PostFilterParams()
            {
                CategorySlug = categorySlug,
                PageId = pageId,
                Take = 1,
                Title = title
            };
            var model = _postService.GetPostsByFilter(param);
            return View(model);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(CreatePostViewModel createViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(createViewModel);
            }
            var result = _postService.CreatePost(new CreatePostDto()
            {
                CategoryId = createViewModel.CategoryId,
                Description = createViewModel.Description,
                ImageFile = createViewModel.ImageFile,
                Slug = createViewModel.Slug,
                SubCategoryId = createViewModel.SubCategoryId == 0 ? null : createViewModel.SubCategoryId,
                Title = createViewModel.Title,
                IsSpecial = createViewModel.IsSpecial,
                UserId = User.GetUserId()
            });

            if (result.Status != OperationResultStatus.Success)
            {
                ModelState.AddModelError(nameof(CreatePostViewModel.Slug), result.Message);
                return View(createViewModel);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var post = _postService.GetPostById(id);
            if (post == null)
                return RedirectToAction("Index");

            var model = new EditPostViewModel()
            {
                CategoryId = post.CategoryId,
                Description = post.Description,
                Slug = post.Slug,
                SubCategoryId = post.SubCategoryId,
                Title = post.Title,
                IsSpecial = post.IsSpecial,
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, EditPostViewModel editViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(editViewModel);
            }

            var result = _postService.EditPost(new EditPostDto()
            {
                CategoryId = editViewModel.CategoryId,
                Description = editViewModel.Description,
                ImageFile = editViewModel.ImageFile,
                Slug = editViewModel.Slug,
                SubCategoryId = editViewModel.SubCategoryId == 0 ? null : editViewModel.SubCategoryId,
                Title = editViewModel.Title,
                PostId = id,
                IsSpecial = editViewModel.IsSpecial
            });
            if (result.Status != OperationResultStatus.Success)
            {
                ModelState.AddModelError(nameof(CreatePostViewModel.Slug), result.Message);
                return View(editViewModel);
            }

            return RedirectToAction("Index");
        }
    }
}

Blog-Web/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.CoreLayer.DTOs.Users;
using Blog.CoreLayer.Services.Users;
using Blog.CoreLayer.Utilities;

namespace Blog_Web.Areas.Admin.Controllers
{
    public class UserController : AdminControllerBase
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index(int pageId = 1)
        {
            return View(_userService.GetUsersByFilter(pageId, 10));
        }
        [HttpPost]
        public IActionResult Edit(EditUserDto editModel)
        {
            var result = _userService.EditUser(editModel);
            if (result.Status != OperationResultStatus.Success)
            {
                ErrorAlert(result.Message);
                return RedirectToAction("Index");
            }
            return RedirectAndShowAlert(result, RedirectToAction("Index"));
        }
        public IActionResult ShowEditModal(int userId)
        {
            var user = _userService.GetUserById(userId);
            return PartialView("_EditUser", new EditUserDto()
            {
                FullName = user.FullName,
                Role = user.Role,
                UserId = userId
            });
        }
    }
}

Blog-Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"]</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="/admin/dist/css/bootstrap-theme.css">
    <link rel="stylesheet" href="/admin/dist/css/rtl.css">
    <link rel="stylesheet" href="/admin/bower_components/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/admin/bower_components/Ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="/admin/dist/css/AdminLTE.css">

    <link rel="stylesheet" href="/admin/dist/css/skins/_all-skins.min.css">

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link rel="stylesheet" href="/admin/dist/css/customize-adminlte.css">
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="modal" id="default_Modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
             
            </div>
        </div>
    </div>
</div>
<div class="wrapper">

    <partial name="_Header"/>
    <partial name="_SideBar"/>

    <div class="content-wrapper">
        @RenderBody()
    </div>
    <footer class="main-footer text-left">
        <strong>
            Copyleft &copy; 2014-2017 <a href="https://adminlte.io">Almsaeed Studio</a> & <a href="http://hosseinizadeh.ir/adminlte">Alireza Hosseinizadeh</a>
        </strong>
    </footer>
</div>
<script src="/admin/bower_components/jquery/dist/jquery.min.js"></script>
<script src="/admin/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script src="/admin/bower_components/fastclick/lib/fastclick.js"></script>
<script src="/admin/dist/js/adminlte.min.js"></script>
<script src="/admin/dist/js/demo.js"></script>
<script src="/js/custom.js"></script>
<script src="/js/global.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<partial name="_ValidationScriptsPartial"/>
<script>
    $(document).ready(function() {
        $('.sidebar-menu').tree();
    })
</script>
@await RenderSectionAsync("Scripts", false)
</body>

</html>

Blog-Web/Areas/Admin/Views/Shared/_Header.cshtml
<header class="main-header">
    <a href="/admin/index.html" class="logo">
        <span class="logo-mini">پنل</span>
        <span class="logo-lg"><b>کنترل پنل مدیریت</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">۴ پیام خوانده نشده</li>
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul class="menu">
                                <li>
                                    <!-- start message -->
                                    <a href="#">
                                        <div class="pull-right">
                                            <img src="/admin/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            علیرضا
                                            <small><i class="fa fa-clock-o"></i> ۵ دقیقه پیش</small>
                                        </h4>
                                        <p>متن پیام</p>
                                    </a>
                                </li>
                                <!-- end message -->
                                <li>
                                    <a href="#">
                                        <div class="pull-right">
                                            <img src="/admin/dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            نگین
                                            <small><i class="fa fa-clock-o"></i> ۲ ساعت پیش</small>
                                        </h4>
                                        <p>متن پیام</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="pull-right">
                                            <img src="/admin/dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            نسترن
                                            <small><i class="fa fa-clock-o"></i> امروز</small>
                                        </h4>
                                        <p>متن پیام</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="pull-right">
                                            <img src="/admin/dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            نگین
                                            <small><i class="fa fa-clock-o"></i> دیروز</small>
                                        </h4>
                                        <p>متن پیام</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="pull-right">
                                            <img src="/admin/dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            نسترن
                                            <small><i class="fa fa-clock-o"></i> ۲ روز پیش</small>
                                        </h4>
                                        <p>متن پیام</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">نمایش تمام پیام ها</a></li>
                    </ul>
                </li>
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">۱۰</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">۱۰ اعلان جدید</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> ۵ کاربر جدید ثبت نام کردند
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-warning text-yellow"></i> اخطار دقت کنید
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-users text-red"></i> ۴ کاربر جدید ثبت نام کردند
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-shopping-cart text-green"></i> ۲۵ سفارش جدید
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-user text-red"></i> نام کاربریتان را تغییر دادید
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">نمایش همه</a></li>
                    </ul>
                </li>
                <!-- Tasks: style can be found in dropdown.less -->
                <li class="dropdown tasks-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">۹</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">۹ کار برای انجام دارید</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <h3>
                                            ساخت دکمه
                                            <small class="pull-left">20%</small>
                                        </h3>
                                        <div class="progress xs">
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                                                 aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">20% تکمیل شده</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <h3>
                                            ساخت قالب جدید
                                            <small class="pull-left">40%</small>
                                        </h3>
                                        <div class="progress xs">
                                            <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar"
                                                 aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">40% تکمیل شده</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <h3>
                                            تبلیغات
                                            <small class="pull-left">60%</small>
                                        </h3>
                                        <div class="progress xs">
                                            <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar"
                                                 aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">60% تکمیل شده</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <h3>
                                            ساخت صفحه فرود
                                            <small class="pull-left">80%</small>
                                        </h3>
                                        <div class="progress xs">
                                            <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar"
                                                 aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">80% تکمیل شده</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">نمایش همه</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="/admin/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                        <span class="hidden-xs">علیرضا حسینی زاده</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="/admin/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                            <p>
                                علیرضا حسینی زاده
                                <small>مدیریت کل سایت</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">صفحه من</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">فروش</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">دوستان</a>
                                </div>
                            </div>
                        </li>
                        <li class="user-footer">
                            <div class="pull-right">
                                <a href="#" class="btn btn-default btn-flat">پروفایل</a>
                            </div>
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">خروج</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

Blog-Web/Areas/Admin/Views/Shared/_Pagination.cshtml
@model Blog.CoreLayer.Utilities.BasePagination
@if (Model.PageCount > 1)
{
    <div class="box-footer">
        <div style="padding:10px">
            <ul class="pagination" style="display: inline-block">
                @if (Model.CurrentPage > 1)
                {
                    <li class="paginate_button previous">
                        <a onclick="changePage(@(Model.CurrentPage-1))" href="#">قبلی</a>
                    </li>
                }
                else
                {
                        
                    <li class="paginate_button previous disabled">
                        <a href="#">قبلی</a>
                    </li>
                }

                @for (var i = Model.StartPage; i <= Model.EndPage; i++)
                {
                    <li class="paginate_button @(i == Model.CurrentPage ? "active" : null)">
                        <a  onclick="changePage(@i)"href="javascript:void(0)">@i</a>
                    </li>
                }
                @if (Model.PageCount > Model.CurrentPage)
                {
                    <li class="paginate_button next">
                        <a onclick="changePage(@(Model.CurrentPage+1))" href="#">بعدی</a>
                    </li>
                }
                else
                {
                    <li class="paginate_button next disabled">
                        <a  href="javascript:void(0)">بعدی</a>
                    </li>
                }
            </ul>
        </div>
    </div>
}

Blog-Web/Areas/Admin/Views/Shared/_SideBar.cshtml
@{
    var selected = ViewData["selected"]?.ToString()?.ToLower();
}
<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            @*<li class="active treeview">
            <a href="#">
                <i class="fa fa-dashboard"></i> <span>داشبرد</span>
                <span class="pull-left-container">
                    <i class="fa fa-angle-right pull-left"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li class="active"><a href="/admin/index.html"><i class="fa fa-circle-o"></i> داشبرد اول</a></li>
                <li><a href="/admin/index2.html"><i class="fa fa-circle-o"></i> داشبرد دوم</a></li>
            </ul>
        </li>*@
            <li class="@(selected=="index"?"active":null)">
                <a asp-area="Admin" asp-controller="Home" asp-action="Index">
                    <i class="fa fa fa-dashboard"></i> <span>داشبرد</span>
                </a>
            </li>
            <li class="@(selected=="users"?"active":null)">
                <a asp-area="Admin" asp-controller="User" asp-action="Index">
                    <i class="fa fa fa-dashboard"></i> <span>مدیریت کاربران</span>
                </a>
            </li>
            <li class="@(selected=="category"?"active":null)">
                <a asp-area="Admin" asp-controller="Category" asp-action="Index">
                    <i class="fa fa-th"></i> <span>دسته بندی ها</span>
                </a>
            </li>
            <li class="@(selected=="posts"?"active":null)">
                <a asp-area="Admin" asp-controller="Post" asp-action="Index">
                    <i class="fa fa-th"></i> <span>مدیریت مقالات</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>